"""Figure generator for the truncated-square (4.8.8) shell paper.

Produces two artefacts:

1. submission/truncsq-shell-figures.typ -- publication figure document.
   Contains: a 20-row data table for the DRAT-certified range
   (n=1..20), per-row corona/comps decomposition demonstrating the
   Corona-Equals-Shell identity (a(n) = |corona|, comps = 1, extra = 0
   throughout), and a plateau/first-difference summary. Compiled to
   PDF via `typst compile`.

2. research/truncsq-shell-understanding.txt -- non-spatial skip
   record. The truncated-square (4.8.8) tiling does not have a
   renderer in figure_gen_utils.document_builder; adding one is a
   shared-lib upgrade out of scope for this OEIS submission. The
   non-spatial publication figure (data table + plateau chart in
   submission/truncsq-shell-figures.pdf) provides the full summary
   that the OEIS submission needs.

DocumentBuilder usage notes:
   `figure_gen_utils.document_builder.DocumentBuilder` supports
   coloring, binary, hex, and triangle figures, but not the 4.8.8
   tiling. The publication figure here is hand-rolled Typst (data
   tables only, no spatial rendering), the same approach as the
   trihex sibling project (oeis-new-trihex-shell/code/
   generate-figures.py).
"""
import json
import os


SEQUENCE_NAME = "truncsq-shell"


def _project_dir():
    return os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def _load_results():
    path = os.path.join(_project_dir(), "research", "solver-results.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _build_typst_document(results):
    lines = []
    lines.append('// Generated by code/generate-figures.py')
    lines.append('#set page(paper: "a4", margin: 2cm, numbering: "1")')
    lines.append('#set text(font: "New Computer Modern", size: 10pt)')
    lines.append('#set par(justify: true)')
    lines.append('')
    lines.append('= Truncated-Square (4.8.8) Shell -- Publication Figures')
    lines.append('')
    lines.append(
        'Sequence definition: minimum size of a connected enclosing shell '
        'for an n-cell connected hole on the truncated-square (4.8.8) '
        'Archimedean tiling, where the complement (exterior) is also '
        'connected.'
    )
    lines.append('')

    lines.append('== Figure 1. DRAT-certified values, n = 1 to 20')
    lines.append('')
    lines.append('#figure(')
    lines.append('  table(')
    lines.append('    columns: 6,')
    lines.append('    align: (right, right, right, right, right, right),')
    lines.append('    stroke: 0.5pt,')
    lines.append(
        '    [*n*], [*a(n)*], [*\\|corona\\|*], [*comps*], '
        '[*\\|c\\|+comps-1*], [*runtime (s)*],'
    )
    for n_str in sorted(results.keys(), key=int):
        rec = results[n_str]
        n = int(n_str)
        a = rec.get("value")
        cs = rec.get("corona_size")
        comps = rec.get("comps")
        identity = (cs or 0) + (comps or 0) - 1
        elapsed = rec.get("elapsed", 0.0)
        lines.append(
            f'    [{n}], [{a}], [{cs}], [{comps}], '
            f'[{identity}], [{elapsed:.1f}],'
        )
    lines.append('  ),')
    lines.append(
        '  caption: [DRAT-certified values of a(n) on the truncated-'
        'square (4.8.8) tiling. Each lower bound a(n) >= k is machine-'
        'verified by a DRAT certificate (checked by drat-trim). '
        '\\|corona\\|: edge-adjacent neighbours of the optimal hole. '
        'comps: connected components of the corona. The fifth column '
        'shows \\|corona\\| + comps - 1, equal to a(n) for every '
        'reported term, consistent with the Corona-Equals-Shell '
        'Theorem (comps = 1 throughout, so a(n) = \\|corona\\|).],'
    )
    lines.append(')')
    lines.append('')

    lines.append('== Figure 2. Plateau structure')
    lines.append('')
    lines.append(
        'The 4.8.8 sequence has six plateaus in the certified range: '
        'a(1) = 4, a(2..5) = 8, a(6..8) = 10, a(9..13) = 12, '
        'a(14..18) = 14, a(19..20) = 16. First differences (cell-cost '
        'jumps between consecutive n):'
    )
    lines.append('')
    lines.append('#figure(')
    lines.append('  table(')
    n_keys = sorted(results.keys(), key=int)
    cols = len(n_keys) + 1
    lines.append(f'    columns: {cols},')
    lines.append(f'    align: (right,) * {cols},')
    lines.append('    stroke: 0.5pt,')
    line_n = '    [*n*],'
    line_d = '    [*a(n)-a(n-1)*],'
    for n_str in n_keys:
        n = int(n_str)
        a_n = results[n_str]['value']
        if n == 1:
            d = '--'
        else:
            a_prev = results[str(n - 1)]['value']
            d = a_n - a_prev
        line_n += f' [{n}],'
        line_d += f' [{d}],'
    lines.append(line_n)
    lines.append(line_d)
    lines.append('  ),')
    lines.append(
        '  caption: [First differences of a(n) on the 4.8.8 tiling. '
        'The leading transition (n = 2) is a +4 jump from a(1) = 4 to '
        'a(2) = 8. Every subsequent transition is +0 (within a '
        'plateau) or +2 (at a plateau boundary). No other delta value '
        'occurs in the proved range; this is Conjecture 3 in the body '
        'of the paper.],'
    )
    lines.append(')')
    lines.append('')

    lines.append('== Figure 3. Corona-Equals-Shell decomposition')
    lines.append('')
    lines.append(
        'On the 4.8.8 tiling the unified shell decomposition '
        'a = |corona| + (comps - 1) + extra reduces to a = |corona|, '
        'because vertex degree 3 implies the corona is connected '
        '(comps = 1) and there are no Steiner bridge cells (extra = '
        '0). This is the Corona-Equals-Shell Theorem (Section '
        'Computational Methodology of the paper). The structural '
        'equality holds for every n in the certified range and is '
        'conjectured to hold for all n on this lattice.'
    )
    lines.append('')

    return "\n".join(lines)


def _write_understanding_skip():
    path = os.path.join(
        _project_dir(), "research", f"{SEQUENCE_NAME}-understanding.txt"
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "skip-understanding: no spatial diagram emitted.\n"
            "\n"
            "Reason: the truncated-square (4.8.8) Archimedean tiling\n"
            "does not have a renderer in figure_gen_utils.\n"
            "document_builder (the shared library supports coloring,\n"
            "binary, hex, and triangle grids; 4.8.8 has square +\n"
            "octagon mixed-cell geometry not directly representable\n"
            "by the existing renderers). Adding a 4.8.8 renderer to\n"
            "figure_gen_utils is recorded as future work. The\n"
            "publication figures (data table + first-difference\n"
            "summary in submission/truncsq-shell-figures.pdf) provide\n"
            "the non-spatial summary that the OEIS submission needs.\n"
        )


def main():
    project_dir = _project_dir()
    submission_dir = os.path.join(project_dir, "submission")
    os.makedirs(submission_dir, exist_ok=True)

    results = _load_results()
    typst = _build_typst_document(results)
    typ_path = os.path.join(
        submission_dir, f"{SEQUENCE_NAME}-figures.typ",
    )
    with open(typ_path, "w", encoding="utf-8") as f:
        f.write(typst)
    print(f"Wrote {typ_path}", flush=True)

    _write_understanding_skip()
    print(
        f"Wrote {os.path.join(project_dir, 'research', f'{SEQUENCE_NAME}-understanding.txt')}",
        flush=True,
    )


if __name__ == "__main__":
    main()
